common: &common
  adapter: postgresql
  encoding: unicode
  username: phase1
  password: phase1

development:
  <<: *common
  database: phase1_development

test:
  <<: *common
  database: phase1_test

production:
  <<: *common
  database: phase1_production
